version: 0.2

phases:
  install:
    runtime-versions:
      # Use the Python version your app was built with (e.g., 3.11)
      python: 3.11 
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  
  pre_build:
    commands:
      # You can keep unit tests here if you have them
      - echo Running pre-build steps...
  
  build:
    commands:
      - echo Running the Atlas Update Script...
      # CRITICAL: Execute your script here
      - python update_atlas.py
      # The script will generate data/atlas-latest.json
      # The script will generate data/atlas-archive.json (based on snippet)

artifacts:
  files:
    # Save the output files from the script
    - 'data/atlas-latest.json'
    - 'data/atlas-archive.json'
  # Set the artifact path if you want to upload the output to a specific S3 location
  # discard-paths: yes