name: Automated Atlas Data Update

on:
  # Cron job runs every day at 7:00 AM UTC AND 4:00 PM UTC
  schedule:
    - cron: '0 7 * * *'
    - cron: '0 16 * * *'

  # This button lets you run it immediately from the Actions tab.
  workflow_dispatch:

jobs:
  run_update:
    # Use a temporary, clean Linux machine for the job
    runs-on: ubuntu-latest

    steps:
      # Step 1: The machine needs your code first!
      - name: Checkout Repository Code
        uses: actions/checkout@v4
        # Grant push access to the default GITHUB_TOKEN (required because you set "Read and write permissions" in Settings)
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      # Step 2: Set up the correct Python environment
      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
          
      # Step 3: Install all required Python libraries (from requirements.txt)
      - name: Install Dependencies
        run: pip install -r requirements.txt
        
      # Step 4: Run the main script, injecting all secure keys
      # Step 4: Run the main script, injecting all secure keys
      - name: Execute Atlas Update Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          # THIS MUST BE PERFECTLY CASE-SENSITIVE AND ALIGNED:
          GOOGLE_SEARCH_API_KEY: ${{ secrets.GOOGLE_SEARCH_API_KEY }}
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: python update_atlas.py

      # Step 5: Commit and Push the updated JSON files back to the repository
      - name: Commit and Push Changes
        run: |
          # Configure the commit author
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Add the generated files to staging
          git add data/atlas-latest.json data/atlas-archive.json
          
          # Commit changes (|| true prevents the job from failing if the files haven't changed)
          git commit -m "Automated: Daily Atlas data update" || true
          
          # Push the commit to your repository
          git push